### CREATE a new bin 
POST http://localhost:3000/api/bins/ 

### GET requests for a bin
GET http://localhost:3000/api/bins/inspect/61c632ce39178846734ae585

### ALL add a request to a bin
GET http://localhost:3000/api/bins/61c632ce39178846734ae585
